[server]
host = "0.0.0.0"
port = 8080
shutdown_timeout = 10000

[logging]
level = "info"
format = "pretty"

[database.postgres]
uri = "postgresql://postgres:password@localhost:5432/emcache"
max_connections = 20
min_connections = 5
connection_timeout = 1000

[sources.main]
uri = "mongodb://mongo.emcache.orb.local:27017/test?directConnection=true"
database = "test"

[cache]
base_dir = "caches"
replication_interval = 10000
entity_refresh_interval = 10000

[snapshot]
cleanup_interval = 10000
staleness_duration = 600000
