[server]
host = "0.0.0.0"
port = 8080

[logging]
# Log level: trace, debug, info, warn, error
level = "info"
# Log format: json, pretty
format = "pretty"

[database.postgres]
uri = "postgresql://postgres:password@localhost:5432/emcache"
max_connections = 20
min_connections = 5
connection_timeout = 1000

[sources.main]
uri = "mongodb://mongo.emcache.orb.local:27017/test?directConnection=true"

[cache]
base_dir = "caches"
