version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: emcachers
      POSTGRES_USER: emcachers
      POSTGRES_PASSWORD: emcachers_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emcachers"]
      interval: 10s
      timeout: 5s
      retries: 5

  emcachers:
    build: .
    environment:
      - POSTGRES_URL=postgresql://emcachers:emcachers_password@postgres:5432/emcachers
      - RUST_LOG=info
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./dbs:/app/dbs
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
