// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/protos/emcache.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OplogEntry_OperationType int32

const (
	OplogEntry_OPERATION_TYPE_UNSPECIFIED OplogEntry_OperationType = 0
	OplogEntry_UPSERT                     OplogEntry_OperationType = 1
	OplogEntry_DELETE                     OplogEntry_OperationType = 2
)

// Enum value maps for OplogEntry_OperationType.
var (
	OplogEntry_OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "UPSERT",
		2: "DELETE",
	}
	OplogEntry_OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"UPSERT":                     1,
		"DELETE":                     2,
	}
)

func (x OplogEntry_OperationType) Enum() *OplogEntry_OperationType {
	p := new(OplogEntry_OperationType)
	*p = x
	return p
}

func (x OplogEntry_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OplogEntry_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protos_emcache_proto_enumTypes[0].Descriptor()
}

func (OplogEntry_OperationType) Type() protoreflect.EnumType {
	return &file_pkg_protos_emcache_proto_enumTypes[0]
}

func (x OplogEntry_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OplogEntry_OperationType.Descriptor instead.
func (OplogEntry_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{4, 0}
}

type DownloadDbRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadDbRequest) Reset() {
	*x = DownloadDbRequest{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDbRequest) ProtoMessage() {}

func (x *DownloadDbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDbRequest.ProtoReflect.Descriptor instead.
func (*DownloadDbRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadDbRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type DownloadDbResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDbResponse) Reset() {
	*x = DownloadDbResponse{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDbResponse) ProtoMessage() {}

func (x *DownloadDbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDbResponse.ProtoReflect.Descriptor instead.
func (*DownloadDbResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadDbResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DownloadDbResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type GetOplogEntriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectionNames []string               `protobuf:"bytes,1,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	AfterIndex      int64                  `protobuf:"varint,2,opt,name=after_index,json=afterIndex,proto3" json:"after_index,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOplogEntriesRequest) Reset() {
	*x = GetOplogEntriesRequest{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOplogEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOplogEntriesRequest) ProtoMessage() {}

func (x *GetOplogEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOplogEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetOplogEntriesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{2}
}

func (x *GetOplogEntriesRequest) GetCollectionNames() []string {
	if x != nil {
		return x.CollectionNames
	}
	return nil
}

func (x *GetOplogEntriesRequest) GetAfterIndex() int64 {
	if x != nil {
		return x.AfterIndex
	}
	return 0
}

func (x *GetOplogEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOplogEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*OplogEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOplogEntriesResponse) Reset() {
	*x = GetOplogEntriesResponse{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOplogEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOplogEntriesResponse) ProtoMessage() {}

func (x *GetOplogEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOplogEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetOplogEntriesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{3}
}

func (x *GetOplogEntriesResponse) GetEntries() []*OplogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type OplogEntry struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Index         int64                    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Operation     OplogEntry_OperationType `protobuf:"varint,2,opt,name=operation,proto3,enum=emcache.OplogEntry_OperationType" json:"operation,omitempty"`
	Id            string                   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Collection    string                   `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
	Data          *structpb.Struct         `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Version       int32                    `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OplogEntry) Reset() {
	*x = OplogEntry{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OplogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogEntry) ProtoMessage() {}

func (x *OplogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogEntry.ProtoReflect.Descriptor instead.
func (*OplogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{4}
}

func (x *OplogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OplogEntry) GetOperation() OplogEntry_OperationType {
	if x != nil {
		return x.Operation
	}
	return OplogEntry_OPERATION_TYPE_UNSPECIFIED
}

func (x *OplogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OplogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OplogEntry) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *OplogEntry) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OplogEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AddCollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddCollectionRequest) Reset() {
	*x = AddCollectionRequest{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollectionRequest) ProtoMessage() {}

func (x *AddCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollectionRequest.ProtoReflect.Descriptor instead.
func (*AddCollectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{5}
}

func (x *AddCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type AddCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollectionResponse) Reset() {
	*x = AddCollectionResponse{}
	mi := &file_pkg_protos_emcache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollectionResponse) ProtoMessage() {}

func (x *AddCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protos_emcache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollectionResponse.ProtoReflect.Descriptor instead.
func (*AddCollectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protos_emcache_proto_rawDescGZIP(), []int{6}
}

var File_pkg_protos_emcache_proto protoreflect.FileDescriptor

const file_pkg_protos_emcache_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/protos/emcache.proto\x12\aemcache\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"<\n" +
	"\x11DownloadDbRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\"D\n" +
	"\x12DownloadDbResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"z\n" +
	"\x16GetOplogEntriesRequest\x12)\n" +
	"\x10collection_names\x18\x01 \x03(\tR\x0fcollectionNames\x12\x1f\n" +
	"\vafter_index\x18\x02 \x01(\x03R\n" +
	"afterIndex\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"H\n" +
	"\x17GetOplogEntriesResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.emcache.OplogEntryR\aentries\"\xdd\x02\n" +
	"\n" +
	"OplogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12?\n" +
	"\toperation\x18\x02 \x01(\x0e2!.emcache.OplogEntry.OperationTypeR\toperation\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"collection\x18\x05 \x01(\tR\n" +
	"collection\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"G\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"?\n" +
	"\x14AddCollectionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\"\x17\n" +
	"\x15AddCollectionResponse2\xff\x01\n" +
	"\x0eEmcacheService\x12G\n" +
	"\n" +
	"DownloadDb\x12\x1a.emcache.DownloadDbRequest\x1a\x1b.emcache.DownloadDbResponse0\x01\x12T\n" +
	"\x0fGetOplogEntries\x12\x1f.emcache.GetOplogEntriesRequest\x1a .emcache.GetOplogEntriesResponse\x12N\n" +
	"\rAddCollection\x12\x1d.emcache.AddCollectionRequest\x1a\x1e.emcache.AddCollectionResponseB&Z$github.com/nrjais/emcache/pkg/protosb\x06proto3"

var (
	file_pkg_protos_emcache_proto_rawDescOnce sync.Once
	file_pkg_protos_emcache_proto_rawDescData []byte
)

func file_pkg_protos_emcache_proto_rawDescGZIP() []byte {
	file_pkg_protos_emcache_proto_rawDescOnce.Do(func() {
		file_pkg_protos_emcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protos_emcache_proto_rawDesc), len(file_pkg_protos_emcache_proto_rawDesc)))
	})
	return file_pkg_protos_emcache_proto_rawDescData
}

var file_pkg_protos_emcache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protos_emcache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_protos_emcache_proto_goTypes = []any{
	(OplogEntry_OperationType)(0),   // 0: emcache.OplogEntry.OperationType
	(*DownloadDbRequest)(nil),       // 1: emcache.DownloadDbRequest
	(*DownloadDbResponse)(nil),      // 2: emcache.DownloadDbResponse
	(*GetOplogEntriesRequest)(nil),  // 3: emcache.GetOplogEntriesRequest
	(*GetOplogEntriesResponse)(nil), // 4: emcache.GetOplogEntriesResponse
	(*OplogEntry)(nil),              // 5: emcache.OplogEntry
	(*AddCollectionRequest)(nil),    // 6: emcache.AddCollectionRequest
	(*AddCollectionResponse)(nil),   // 7: emcache.AddCollectionResponse
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 9: google.protobuf.Struct
}
var file_pkg_protos_emcache_proto_depIdxs = []int32{
	5, // 0: emcache.GetOplogEntriesResponse.entries:type_name -> emcache.OplogEntry
	0, // 1: emcache.OplogEntry.operation:type_name -> emcache.OplogEntry.OperationType
	8, // 2: emcache.OplogEntry.timestamp:type_name -> google.protobuf.Timestamp
	9, // 3: emcache.OplogEntry.data:type_name -> google.protobuf.Struct
	1, // 4: emcache.EmcacheService.DownloadDb:input_type -> emcache.DownloadDbRequest
	3, // 5: emcache.EmcacheService.GetOplogEntries:input_type -> emcache.GetOplogEntriesRequest
	6, // 6: emcache.EmcacheService.AddCollection:input_type -> emcache.AddCollectionRequest
	2, // 7: emcache.EmcacheService.DownloadDb:output_type -> emcache.DownloadDbResponse
	4, // 8: emcache.EmcacheService.GetOplogEntries:output_type -> emcache.GetOplogEntriesResponse
	7, // 9: emcache.EmcacheService.AddCollection:output_type -> emcache.AddCollectionResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_protos_emcache_proto_init() }
func file_pkg_protos_emcache_proto_init() {
	if File_pkg_protos_emcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protos_emcache_proto_rawDesc), len(file_pkg_protos_emcache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protos_emcache_proto_goTypes,
		DependencyIndexes: file_pkg_protos_emcache_proto_depIdxs,
		EnumInfos:         file_pkg_protos_emcache_proto_enumTypes,
		MessageInfos:      file_pkg_protos_emcache_proto_msgTypes,
	}.Build()
	File_pkg_protos_emcache_proto = out.File
	file_pkg_protos_emcache_proto_goTypes = nil
	file_pkg_protos_emcache_proto_depIdxs = nil
}
